# Generated by Django 4.2 on 2023-04-15 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=10)),
                ("sell_value", models.FloatField()),
                ("buy_value", models.FloatField()),
                ("current_price", models.FloatField()),
                ("action", models.CharField(max_length=5)),
            ],
        ),
    ]
